### PR TITLE
re #264 Ability to add custom forms

### PR DESCRIPTION
**Pull request by kahboom**
**Changes:**
- Add `Super Duper` policy (basically a clone of the Soap Authorization policy with adjustments made).
- Add `Custom` policy definition type to enum

--

**Screenshots:**

_Manager UI Code:_
screen shot 2016-05-09 at 7 55 28 pm
screen shot 2016-05-09 at 7 55 53 pm
screen shot 2016-05-09 at 8 01 27 pm
screen shot 2016-05-09 at 8 02 59 pm

_apiman Plugins Code (separate repo, PR):_
screen shot 2016-05-09 at 6 45 27 pm

_In the UI:_
apiman admin plugins

--

**JIRA**: https://issues.jboss.org/browse/APIMAN-264

cc @EricWittmann

### CODE REVIEW

**Comment by EricWittmann** [comment]
Is this ready to be reviewed and merged?  If so, can you clean up the PR so it includes a small # of commits (ideally 1) and doesn't include all of the dev portal related files?

**Comment by kahboom** [comment]
@EricWittmann - Not ready, I'll try to finish this up ASAP. Still need to add some methods for validation and documentation.

**Comment by EricWittmann** [comment]
OK, let's close the PR then.

**Comment by EricWittmann** [comment]
You can open a new one whenever it's ready.  No rush as I know you're working on other tasks/projects now.

**Pull request closed without merging**
