### PR TITLE
APIMAN-1347, custom plugin loading during deployment problem fixed

### PR DESCRIPTION
**Pull request by potehvad**
Please include fix of plugin deployment bug also in docker images.

### CODE REVIEW

**Comment by potehvad** [comment]
> I can't say I know why this would fix APIMAN-1347 but it's definitely plausible. :) @msavy any objection to merging this?

The reason of plugin failure is that wildfly deploys apiman-gateway.war and apiman-gateway-api.war simultaneously. So both performing actions with plugins simultaneously. Once first is in process of unzipping files to .work directory, empty libs already exist on file system and second deployment entry thinks that libs is ready to be loaded. Once it is empty it throws errors.

**Comment by EricWittmann** [comment]
I see!  Thanks for the explanation.  That makes a lot of sense and I now understand what is happening.

**Comment by bekihm** [comment]
We tested the current master on windows and get an error while the renaming step:
```
java.io.FileNotFoundException: C:\data\git\apiman\common\plugin\target\_plugintmp\plugin-with-depResource.war\lib\activemq-client-5.13.2.jar (The system cannot find the file specified)

	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at io.apiman.common.plugin.PluginClassLoader.extractDependency(PluginClassLoader.java:140)
	at io.apiman.common.plugin.PluginClassLoader.indexPluginArtifact(PluginClassLoader.java:99)
	at io.apiman.common.plugin.PluginClassLoader.<init>(PluginClassLoader.java:59)
	at io.apiman.common.plugin.PluginClassLoaderTest$TestPluginClassLoader.<init>(PluginClassLoaderTest.java:158)
	at io.apiman.common.plugin.PluginClassLoaderTest.testGetResourceFromDep(PluginClassLoaderTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
We found the cause: Before you rename the file you have to close the OutputStream in two methods of io.apiman.common.plugin.PluginClassLoader.
```java 
IOUtils.copy(input, output);
output.close();
tmpFile.renameTo(depFile);
```
Only flushing the stream does not release the lock of the file.

**Comment by EricWittmann** [comment]
OK so we need another PR to fix that, correct?

**Comment by bekihm** [comment]
Yes, I can deliver it.

**Comment by bekihm** [comment]
Created [PR-729](https://github.com/apiman/apiman/pull/729).

**Pull request merged**
