### PR TITLE
apiman-1318: Export/Import of a plugin with policies does not work because of its ID

### PR DESCRIPTION
**Pull request by volkflo**
See also: https://issues.jboss.org/projects/APIMAN/issues/APIMAN-1318

This may be not the ultimate solution but it is working for us at the moment.

Please let me know what you think.

### CODE REVIEW

**Comment by msavy** [comment]
Eric and I discussed this and we think it looks good. 

Have you done any testing on this? Have you noticed any issues?

**Comment by volkflo** [comment]
Thanks for your answer Marc.

Yes I tested this with some configurations via Export/Import and also as basic configuration at the first startup of apiman in tomcat. This is working for me.
Unfortunately, I could only test with elasticsearch and not with any database.

The tests are all good on windows and linux, but one of your travis-tests failed. I don't checked why.

**Comment by msavy** [comment]
Thanks for your patience. I've finally slayed all of the bugs (hopefully) from the ES 5.x upgrade. 

I'll asses, merge, and test your work after that's on master.

**Comment by msavy** [comment]
Thank you for your contribution, it's much appreciated 🎉

**Pull request closed without merging**
