### PR TITLE
build(pom): Update to 5.3.2 Jest client from 0.1.7

### PR DESCRIPTION
**Pull request by msavy**
Enables Metrics to work with ES 5.x.

### CODE REVIEW

**Comment by msavy** [comment]
Any possible issues you can think of @EricWittmann?

**Comment by msavy** [comment]
Causes a failure on manager (still older version of ES running, just client changed). Slightly weird error, not quite sure yet, but looking into it. Most tests pass.

```
io.apiman.manager.api.core.exceptions.StorageException: io.apiman.manager.api.core.exceptions.StorageException: \"InvalidTypeNameException[mapping type name [auditEntry,api,apiVersion,apiPolicies,contract] should not include , in it]\"","moreInfoUrl":null,"stacktrace":"io.apiman.manager.api.rest.contract.exceptions.SystemErrorException: io.apiman.manager.api.core.exceptions.StorageException: io.apiman.manager.api.core.exceptions.StorageException: \"InvalidTypeNameException[mapping type name [auditEntry,api,apiVersion,apiPolicies,contract] should not include , in it]\"
    at io.apiman.manager.api.rest.impl.OrganizationResourceImpl.deleteApi(OrganizationResourceImpl.java:418)
    at io.apiman.manager.api.rest.impl.OrganizationResourceImpl$Proxy$_$$_WeldClientProxy.deleteApi(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at io.apiman.common.servlet.RootResourceFilter.doFilter(RootResourceFilter.java:59)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:57)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at io.apiman.manager.api.security.impl.DefaultSecurityContextFilter.doFilter(DefaultSecurityContextFilter.java:56)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at io.apiman.common.servlet.AuthenticationFilter.doFilterChain(AuthenticationFilter.java:272)
    at io.apiman.common.servlet.AuthenticationFilter.doBasicAuth(AuthenticationFilter.java:240)
    at io.apiman.common.servlet.AuthenticationFilter.doFilter(AuthenticationFilter.java:194)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: io.apiman.manager.api.core.exceptions.StorageException: io.apiman.manager.api.core.exceptions.StorageException: \"InvalidTypeNameException[mapping type name [auditEntry,api,apiVersion,apiPolicies,contract] should not include , in it]\"
    at io.apiman.manager.api.es.EsStorage.deleteApi(EsStorage.java:843)
    at io.apiman.manager.test.server.TestEsStorageWrapper.deleteApi(TestEsStorageWrapper.java:346)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
    at io.apiman.manager.api.core.IStorage$1886942614$Proxy$_$$_WeldClientProxy.deleteApi(Unknown Source)
    at io.apiman.manager.api.rest.impl.OrganizationResourceImpl.deleteApi(OrganizationResourceImpl.java:410)
    ... 49 more
Caused by: io.apiman.manager.api.core.exceptions.StorageException: \"InvalidTypeNameException[mapping type name [auditEntry,api,apiVersion,apiPolicies,contract] should not include , in it]\"
    at io.apiman.manager.api.es.EsStorage.deleteApi(EsStorage.java:840)
    ... 58 more
```

**Comment by msavy** [comment]
Interesting, the failures all seem to be either deletes or deliberate testing of errors (e.g. get an API that doesn't exist).

**Comment by EricWittmann** [comment]
Without digging into it I don't have much insight for you.  If you get stuck let me know and I can have a look.

**Comment by ulaBLUE** [comment]
I did some analysis before as we wanted to move ES to latest version but seemingly the current apiman 1.3 versions only supports to upgrade to ES 2.x version. And while we upgraded to ES 2.2.4 version, we have recently noticed that there is some periodic exception during operations like policy (Ratelimiting policy) check. On further investigation, I found that Jest client itself has compatibility (https://github.com/searchbox-io/Jest#compatibility) with ES version. With ES 2.2.4 version, the JEST client needs to be 2.x version only. Although I haven't tried to compile 2.x  versions myself. I shall be doing it now and share my results.

**Comment by msavy** [comment]
@ulaBLUE thanks; be interested to hear your results. 

I've been working on a branch locally to experiment with ES 5.x compatibility as the newer versions of Jest don't work properly for ES 1.x (as you correctly point out, the docs indicate they don't guarantee that anymore).

My current plan is to keep 2 sets of ES plugins, registries and components: ES 1.x and ES 2.x-5.x (I think 2.x+ and 5.x+ are fairly compatible, but I'm not completely sure yet). Quite a few changes will be needed, so plenty of care will be needed.

The major caveat is that users would need to ensure that you don't _mix and match_ 1.x compatible and 2.x+ compatible plugins in the same JVM as it will cause JAR hell for the Jest driver, and some horrible mess will ensue!

FWIW, the existing ES Metrics implementation works OK with the updated Jest driver, so if you only want ES 2.x/5.x metrics in the interim you can compile this version and copy over the metrics impl (ESMetricsImpl). Caveats as above, though.

These changes won't be in the release that'll be pushed out today (or perhaps tomorrow), as it's too much late disruption. Probably scheduled for the very near future, though.

**Comment by donovanmuller** [comment]
Any idea when this will be released? I'm still running a `SNAPSHOT` build while waiting for this to be  resolved.

**Comment by msavy** [comment]
Hi @donovanmuller, apologies for the slow response - I missed it on GH.

Looking to get it in for the release after next. 

The currently pending release should be out shortly (assuming I can get it out before or during my SA trip). 

It won't be included in this release due to the relatively high risk of that change.

The following release come just a few weeks after this one as it has several changes which are easy to implement (or already done) but can't be sensibly put into a single release.

**Comment by msavy** [comment]
This has been superseded, see: #662

**Pull request closed without merging**
