### PR TITLE
Caching resources policy

### PR DESCRIPTION
**Pull request by bekihm**
We present now the PR for the Caching Resources Policy like already announced in this [issue](https://github.com/apiman/apiman/issues/737 ).
You can cache requests based on their URL path, http method and specific status code.
2019-07-18 15_37_35-API Management - Add Policy

We allow also wildcards to support the cache-all functionality of the old Caching Policy. So we marked the Caching Policy as deprecated:
2019-07-17 11_02_45-API Management - Add Policy

There are also new test cases for the policy to ensure that caching works in all cases. The documentation will follow in case you accept the new policy.

Special thanks to @volkflo for reviewing and testing this new policy multiple times.

We hope you will enjoy this new policy.

### CODE REVIEW

**Comment by EricWittmann** [comment]
I'll merge this on 2019-07-24 if there are no objections before then.

**Comment by bekihm** [comment]
@EricWittmann I will add another feature that the request body is also considered for caching. This is important for POST request caching.

**Comment by msavy** [comment]
Sounds good. Are you going to attach that to this commit, or are you going to make a new one?

**Comment by bekihm** [comment]
@msavy I can attach it to this PR, if you want.

**Comment by EricWittmann** [comment]
Let's do a separate PR for that.  I'll merge this tomorrow, as scheduled.  Then you can follow that up with the POST improvement.

**Comment by bekihm** [comment]
@EricWittmann ok, I added only a little fixup in class CachingResourcesPolicy which used the CachingPolicy.class as key name (CachingResourcesPolicy.java line 35 - 39). Now it uses its own class for for the context keys.

**Comment by bekihm** [comment]
@EricWittmann  I prepared the user guide documentation for the new policy. So I can open a PR for this if the policy is merged.

**Comment by EricWittmann** [comment]
@bekihm merged!  Thanks for the contribution.

**Pull request merged**
