### PR TITLE
adding .editconfig

### LINKED ISSUE #925: should we have EditorConfig for every IDE?
# What is EditorConfig?
_EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems._
https://editorconfig.org

### PR DESCRIPTION
**Pull request by juniorjainsahab**
fix #925 
These are some common configurations that work in every IDE and can be changed in the future if needed.

### CODE REVIEW

**Comment by volkflo** [comment]
How are these settings applied? Does the IDE detect this automatically? :)

In general, there are already IDE configs located here: https://github.com/apiman/apiman/tree/master/tools/src

**Comment by juniorjainsahab** [comment]
@volkflo most of the IDE's detect them automatically but some IDE's listed [here](https://editorconfig.org/#download) requires the installation of a plugin to understand these configurations.

**Comment by bekihm** [comment]
I read that for eclipse one needs a plugin and IntelliJ detects the config file automatically.

**Comment by EricWittmann** [comment]
These are pretty simple rules - so I'm OK with it.  Not sure about the LF vs. CRLF setting when using a Windows machine.  Typically that conversion is handled by git, so am not sure it's needed.

The formatting rules linked to by @volkflo are much more advanced.

**Comment by volkflo** [comment]
@juniorjainsahab Do you know what happens if we apply this in a windows machine are then existing line breaks changed to LF?

**Comment by juniorjainsahab** [comment]
@volkflo I am not sure of it but I don't think so that it will work differently on windows.

**Review by volkflo — APPROVED** [review]

**Comment by volkflo** [comment]
@EricWittmann The changes are okay for me as well, so I let it up to you if we merge this or not :)

**Pull request merged**
