### PR TITLE
Updated the swagger WSDL code to be namespace aware

### PR DESCRIPTION
**Pull request by EricWittmann**
This update should make the algorithm much more robust when processing WSDL files.

### CODE REVIEW

**Comment by EricWittmann** [comment]
@volkflo @tevosouza @bekihm Have a look at this update and let me know what you think.  It should do the same thing as before but better. :)

**Comment by EricWittmann** [comment]
Note: there are some failing unit tests, but I think failing due to another change, not mine.  I'll fix those and update this PR.

**Comment by EricWittmann** [comment]
OK I was missing a couple things in this PR - will work on it tomorrow and update here when ready. :)  Stay tuned.

**Comment by EricWittmann** [comment]
OK this is now ready to review.  I believe all unit tests are green and the code actually makes sense.  I had to dig out all of my old WSDL/XML/SOAP knowledge from years ago, dust it off, shake it out, and try to make sense of it.  :)  But I think this is now the right approach!

**Comment by tevosouza** [comment]
LGTM!
Thanks @EricWittmann

**Comment by EricWittmann** [comment]
Thanks everyone.  What a great throwback problem!  :)

**Pull request merged**
