### PR TITLE
Handle LDAP issue when error when certain errors when using ServiceAccount can be blackholed

### PR DESCRIPTION
**Pull request by msavy**

### CODE REVIEW

**Comment by msavy** [comment]
cc @jcechace @xjaros1

**Comment by EricWittmann** [comment]
Do we need to add a unit test for this?

**Comment by msavy** [comment]
Yeah, and I think a bit of control flow needs changing - it's a bit awkward to the interface, but it seems in this case it'll cause a 500 error which is kinda uninformative. Will reopen when done.

**Comment by jcechace** [comment]
Thanks for the mention, the fix should be verified tonight (when the ci job gets triggered)

**Comment by msavy** [comment]
No Problem! I’m making some improvements and will reopen the commit later.

**Comment by msavy** [comment]
OK, have revised this.

**Comment by msavy** [comment]
@EricWittmann - OK should be good now

**Pull request merged**
