### PR TITLE
Reverted #809

### PR DESCRIPTION
**Pull request by EricWittmann**
OK @volkflo and @bekihm  and @tevosouza - have a look.  This is a reversion of #809.  Can you verify?

### CODE REVIEW

**Comment by volkflo** [comment]
I think this is good for the moment and makes the UI usable again :)
I hope this gets reworked by the author because I think these are nice changes if they are checked again. But you have to compare what validation was already done

**Comment by bekihm** [comment]
Thanks @EricWittmann for the revert 👍 
I think we will test tomorrow :-)

Maybe we have a chance that the author reworks the policy validation again see [here](https://github.com/apiman/apiman/pull/833)

**Comment by tevosouza** [comment]
I've made superficial tests and I think that is ok, I have found one problem with API definition (wsdl), but it's not related to PR #809.
Thanks @EricWittmann for the revert ;)

**Comment by volkflo** [comment]
@tevosouza If the WSDL Problem is that you cannot delete it correctly then I will provide a PR soon :)

**Comment by EricWittmann** [comment]
OK I wasn't sure if this was the correct PR to revert, because I couldn't find any regexp changes in there.  There are some validation changes for sure, but also a lot of security related fixes.  So please give this some testing and make sure it's what needs to be reverted.  :)

**Comment by EricWittmann** [comment]
Oh, and just "@EricWittmann" here when we're ready to merge!

**Comment by volkflo** [comment]
@EricWittmann I tested this, everything in the UI is working again 👍

**Pull request merged**
