### PR TITLE
re #803 Switch from bootstrap-select to UI-select

### PR DESCRIPTION
**Pull request by kahboom**
Changes:
- Switch to UI-select for the following views: Service Implementation tab, Service Definition tab, Service Plans tab, New Contract (&modal)
- Re-add validation for some UI-select dropdowns that were misbehaving
- Removed some expensive `$watch`'s but there are still many improvements that need to be made in ongoing PRs.
- Style for consistency on respective pages
- Fix an unrelated console error for User Profile page that I noticed a while ago
- Moved the `UserProfile` controller to the `/ts/user` dir, with the rest of the user stuff.
- Other minor cleanup for unused functionality or markup

The dropdowns should look very similar, with the exception of the ability to search for items. I've disabled this feature for dropdowns where it wouldn't make much sense, such as for versions. See screenshots below:

screen shot 2015-12-02 at 12 05 16 pm

screen shot 2015-12-02 at 12 06 24 pm

JIRA: https://issues.jboss.org/browse/APIMAN-803

We are still missing something like 20-22 views. The hard part was re-adding validation for a stubborn dropdown that was misbehaving (specifically the Gateway dropdown), and also removing some of the `$watch`'s. There are still a few improvements that need to be made, but since this is lower priority it will have to be done incrementally over several PRs.

cc @EricWittmann - Sorry for the huge PR; I'll try to keep it shorter next time.

### CODE REVIEW

**Comment by EricWittmann** [comment]
So I'm testing this out, and the UI for ui-select seems to be quite a bit worse than bootstrap-select.  I'll add some screenshots to show what I'm seeing...

image

image

Some things to note about the screenshots:

* The text leaves the bounds of the control
* The dropdown doesn't seem to be sized appropriately to fit the content.  For example, the Version drop-down is like 200px wide even though the options are "1.0" and "2.0".
* The filter box works but isn't as nice as the bootstrap-select version
* When clicking a box, the content is replaced with a text box (the filter) which is smaller vertically than the select box, resulting in the page content shifting up and down as the drop-down is clicked and then an option is selected.

**Comment by kahboom** [comment]
@EricWittmann - That looks terrible. What browser are you using? I'll try to replicate and see what's going on, sorry about that.

**Comment by kahboom** [comment]
Actually I was just about to replicate it on Chrome. Working on this now.

**Comment by kahboom** [comment]
Fixed this locally yesterday, just styling it to make it look as closely to before as possible.

**Comment by kahboom** [comment]
Fixed all of the above issues (on Chrome, need to do additional testing). Some additional changes made:
- Change theme to 'select2' globally, to bring back the same functionality as before in terms of the search and auto width features.
- Set dropdowns to have search disabled by default, and enable manually if needed.
- Disabled/enabled search in places where it made most sense.
- Fixed issue where content was being shifted up and down when opening a dropdown.
- Styling adjustments, including the dropdown button and options, to look nearly identical to how it was before.

#### Screenshots:

<b>Removed search field by default, adjusted styling:</b>

screen shot 2015-12-03 at 10 38 20 am

screen shot 2015-12-03 at 10 38 38 am

screen shot 2015-12-03 at 10 38 50 am

<b>Disabled dropdowns:</b>

screen shot 2015-12-03 at 10 39 10 am

<b>Widths are adjusted automatically and remain centered:</b>

screen shot 2015-12-03 at 10 39 54 am

screen shot 2015-12-03 at 10 40 03 am

screen shot 2015-12-03 at 10 40 17 am

@jcechace - I'm assuming the tests you were running that were failing are E2E tests? How do you run them? Would it be possible for you to run those tests using this fork before we merged it in?

cc @EricWittmann

**Comment by EricWittmann** [comment]
I just pulled everything again, rebuilt, and tested (when deployed to wildfly).  I haven't tested using gulp yet as I'm in the middle of making some rather destructive changes locally.  However, there seem to be lots of UI issues with ui-select.  Here are some screenshots:

image

image

I ran into a bug (my own) that's preventing me from testing further - once I fix that I will keep testing and add more screenshots.

**Comment by EricWittmann** [comment]
Note: I'm testing in Firefox.

@kahboom - your screenshots look great!  I'm looking forward to seeing that on mine. :)

**Comment by kahboom** [comment]
@EricWittmann - That looks like the select2 CSS is not getting pulled in at all for some reason. Taking a look now.

**Comment by kahboom** [comment]
@EricWittmann - This should be working now, retested deployed to WF on Chrome and Firefox.

**Comment by jcechace** [comment]
@kahboom not exactly end-to-end, There is usually test just for specific action (create new service, add version to existing service, add policy X to existing service, publish existing service...). Other than that these are standard selenium test. Also yes, I will trigger a build on your branch.

**Comment by jcechace** [comment]
@kahboom seems I will have to fix the selectors first as we are now using a different select component (the dark side of selenium testing... it breaks, often...). Are there any plans to use select2 for all selects across the UI? I've noticed that mostly bootstrap dropdown is still used.

**Comment by kahboom** [comment]
@jcechace - Ahh, yeah I see what you mean. As far as I know, the goal is to ultimately switch to UI-select for all dropdowns eventually. It's kind of low priority though, so won't happen immediately.

I'm not sure if you're using Protractor to run tests with Selenium-controlled browsers, but I've found that when using Protractor the easiest thing for test maintainability was to target Angular models instead of HTML elements or their attributes. So, for instance, using: `var input = element(by.model('person.name'));`. If you're not using Protractor, that's fine as well, but will tend to make tests more susceptible to minor changes made in the UI.

**Comment by kahboom** [comment]
@EricWittmann @jcechace - I updated the PR to pass the policy definition ID to the backend, and included some very basic validation for it.

**Comment by jcechace** [comment]
@kahboom can confirm. Id is passed correctly now. 

on a side note: the test are (unfortunately) not written in protractor -- we use java. However I think that the by.model selector is in fact corresponding to the "ng-model" attribute, correct? This actually reminded me that I intended to ask you whether it is safe to use this attribute as "unique" identifier. Having id attribute on every element would be nice but hardly possible -- "ng-model" on the other side is there by default due to the nature of angular.

**Comment by jcechace** [comment]
@kahboom app version select is not populated by default when creating new contract 

see https://www.dropbox.com/s/uqjxr4c27fquqsj/apiman_contract_missing_app_version.png?dl=0

**Comment by kahboom** [comment]
@jcechace - That is correct, they do correspond. For other elements that do not correspond to a model, I try to avoid using the `id` attribute and prefer to add a specific CSS class when possible.

Here are some examples that I'm sure you're already familiar with:
`driver.findElement(By.cssSelector("input[ng-model="example"]"))`
`driver.find_element(:css, 'input[ng-model="example"]')`

Or with XPATH:
`driver.findElement(By.xpath("//select[@ng-model='example']"))`

Apologies for the app version select not being populated by default; I'll take a look now. This is a good example of why it might be a good idea for us devs to have E2E tests to run as well before opening a PR, or even as part of the tests included in the Travis build. Normally you wouldn't identify these bugs until the PR is merged in, and if a test fails, it's easier for us to fix on the spot and determine what other tests are failing after, if any, then fix those issues right away, etc. instead of wasting so much of your time. Maybe @EricWittmann can provide some thoughts on this?

**Comment by jcechace** [comment]
@kahboom @EricWittmann We actually intend to setup most of our tests publicly soon (early next year). So I was thinking about setting up the selenium tests with trevis + saucelabs. End-to-End scenarios are also on the roadmap (however even what we have now is able to catch bugs like these).

**Comment by kahboom** [comment]
@jcechace - Please re-test. I didn't get a chance to do a thorough test so I'm not sure that it will be the correct solution. I'll continue to do additional testing tomorrow morning. Thanks! :)

**Comment by jcechace** [comment]
@kahboom Looks fine. There were some issues, however at the moment I am unsure what exactly these are (most likely our tests not being updated). 

Could you rebase your branch so that it's up to date with master?

**Comment by EricWittmann** [comment]
She probably won't be able to do that for a few days.  I'm still working on extensive refactoring on master.  When that's done we can rebase the outstanding PRs.  Should be another day or two.

**Comment by jcechace** [comment]
OK, thanks for the info

**Comment by kahboom** [comment]
Fixed some conflicts and tested on Chrome without issues. I'll keep testing on Safari and FF later today.

@jcechace  - Many incoming changes, so once the Travis build completes it would be great if you could re-run your tests to see if everything is okay.

@EricWittmann - If everything looks good to you and @jcechace 's tests pass, feel free to merge it in.

**Comment by kahboom** [comment]
Closing. Please see: https://github.com/apiman/apiman/pull/301

**Pull request closed without merging**
