### PR TITLE
Standalone WARs for Tomcat

### PR DESCRIPTION
**Pull request by outofcoffee**
# Purpose

Adds Maven modules to build standalone WAR files that can be deployed on Tomcat. The following WARs are built:

  * Gateway
  * Gateway API
  * Elasticsearch embedded

# Rationale

The design intent seems clear that _apiman_'s Gateway and Gateway API should support non-JBoss/Wildfly containers. At present, however, the WARs built by the main project exhibit coupling to JBoss/Wildfly that prevents them from being portable to simple web application containers, such as Tomcat.

# Implementation

The standalone WARs are based on the _apiman_ micro WAR implementation.

Presuming you have completed the normal _apiman_ build process (`mvn clean install`) then you should have the following WAR files already built:

    standalone
    |--api
       |--target/apiman-gateway-api.war
    |--gateway
       |--target/apiman-gateway.war
    |--es
       |--target/apiman-es.war

## Deployment

These instructions been tested on Tomcat 8 (apache-tomcat-8.0.30 to be precise).

  1. Copy the WAR files to your Tomcat `webapps` directory
  2. Add a role and users to `conf/tomcat-users.xml`

Example user and role config:
  
    
    <role rolename="apipublisher"/>
    
    
    <user username="admin" password="admin123!" roles="apipublisher"/>

Once you have deployed the WAR files and configured security, start Tomcat. You should see the WARs get deployed successfully (see the Tomcat logs).

You can access them at:

  * http://localhost:8080/apiman-gateway-api
  * http://localhost:8080/apiman-gateway
  * http://localhost:8080/apiman-es

## Dependencies

  * Since Tomcat (<=8) doesn't provide a CDI implementation, we use JBoss Weld.
  * Currently expects an Elasticsearch instance running on port `localhost:9200` with a cluster named _apiman_. In order to get up and running quickly, you can use the ES embedded WAR, but a proper Elasticsearch cluster is strongly recommended.

# More detail

See the `README.md` at https://github.com/outofcoffee/apiman/blob/feature/standalone-wars/gateway/platforms/war/standalone/README.md

### CODE REVIEW

**Comment by EricWittmann** [comment]
Thanks for working on this.  Standalone WARs would be a welcome addition to the codebase, certainly.  I'm having a little trouble with the PR - it seems that a lot of commits have been dragged into it.  To the extent that github won't even show all the diffs.

If you can easily clean up the PR and resubmit it with just your changes vs. master, that'd be super helpful.  If not, that's OK it will just take me a lot longer to sort through it. :)

**Comment by outofcoffee** [comment]
Thanks for your quick reply @EricWittmann. I'll work on tidying up the PR for you :)

Could you give me some quick direction on which branch I should be tracking? When I started this I used the `1.1.9.Final` tag as the last stable version, but I can see `master` has moved forward now quite a bit. Would it be sensible for me to start from a more recent branch?

**Comment by EricWittmann** [comment]
Yeah Marc and I were just discussing that.  Looks like your work was all based off 1.1.7.  My recommendation is to rebase against the `1.1.x` branch and then I can port it over to `master` easily enough.

**Comment by msavy** [comment]
Ah I see it's based on 1.1.9.Final. Missed that, sorry!

@outofcoffee You should be able to just open a PR against the 1.1.x branch.

**Comment by msavy** [comment]
Looks like it would merge cleanly, too

image

**Comment by outofcoffee** [comment]
Superseded by #308.
Thanks @msavy, @EricWittmann!

**Pull request closed without merging**
