### PR TITLE
feat(policies): add ip granularity to transfer quota policy

### PR DESCRIPTION
**Pull request by volkflo**
Added IP address to the granularity of the transfer quota policy. Furthermore added some unit tests for the policy.

Closes: #1869

### CODE REVIEW

**Comment by volkflo** [comment]
Thanks to @BastianGem who made this changes. I just pushed this PR.

**Review by msavy — APPROVED** [review]
If I understand correctly this is mostly a UI change and is just exposing some functionality that is already there underneath the covers. Is that correct? If so, happy to approve.

**Comment by volkflo** [comment]
@msavy exactly, everything was already there, only the UI part was missing. @BastianGem also added a bunch of tests.

**Review by msavy — APPROVED** [review]

**Comment by msavy** [comment]
Closed via https://github.com/apiman/apiman/commit/e26cd9a03fef75729eaf32ba066cd2ec5ec0ef71

**Comment by msavy** [comment]
Thank you for your contribution @BastianGem, it's appreciated

**Pull request closed without merging**
