### PR TITLE
Vert.x 3 gw config improvements

### PR DESCRIPTION
**Pull request by msavy**
As we discussed a while ago. Very simple; seems to work well for all of our use-cases, I believe.

Example:
```
 { "country": { "seychelles": ["praslin", "mahe"], "mauritius": ["port louis"] } }
```
Becomes:
```
 country.seychelles=praslin,mahe
 country.seychelles=port louis
```
See tests for more examples.

### CODE REVIEW

**Comment by EricWittmann** [comment]
Tests are failing (only the vert.x ones).  I didn't check on the failure to see if it was relevant though.  Give it a look and just let me know if I should merge.

**Comment by msavy** [comment]
Will just be a configuration thing. Will fix and update PR shortly.

**Comment by msavy** [comment]
Looks like I still haven't ironed out a last issue. Will work on later :-).

**Comment by msavy** [comment]
By which I mean... right now!

**Pull request merged**
