### PR TITLE
Add new bundles : Apiman Gateway & Apiman Gateway API

### PR DESCRIPTION
**Pull request by cmoulliard**
Based on the distribrution of Timcat8, 3 bundles have been created (and features file updated) to install Apiman on Karaf

- Apaiman Gateway  OSGI (= Web application of the Gateway). This module works
- Apiman Gateway OSGI Api (= Web Application of the API) 
- Apiman Gateway OSGI Servlet (code of the WarEngineConfig adapted to load the apiman.properties using OSGI Config Admin)

### CODE REVIEW

**Comment by EricWittmann** [comment]
Can you re-submit on the /karaf branch instead of the /master branch?

**Comment by cmoulliard** [comment]
Sorry.

On Fri, Feb 5, 2016 at 6:45 PM, Eric Wittmann <notifications@github.com>
wrote:

> Can you re-submit on the /karaf branch instead of the /master branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apiman/apiman/pull/357#issuecomment-180464750>.
>



-- 
Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by cmoulliard** [comment]
The problem occurs when the PluginRegistry will be created
https://www.dropbox.com/s/r6qm3vo5l7w1kk5/Screenshot%202016-02-05%2019.14.03.png?dl=0
IPluginRegistry & IDataEncrypter have been created but after I don't see
any error even if I can debug till here

    @Override
    protected IRegistry createRegistry(IPluginRegistry pluginRegistry,
IDataEncrypter encrypter) {
        Class<? extends IRegistry> c =
engineConfig.getRegistryClass(pluginRegistry); <-- THAT BREAKS HERE -->
        Map<String, String> config = engineConfig.getRegistryConfig();
        IRegistry registry = create(c, config);
        return new SecureRegistryWrapper(registry, encrypter);
    }

https://www.dropbox.com/s/su3j8rf4irf2511/Screenshot%202016-02-05%2019.22.05.png?dl=0
https://www.dropbox.com/s/pyti6roiul75v6b/Screenshot%202016-02-05%2019.22.41.png?dl=0


On Fri, Feb 5, 2016 at 6:46 PM, Charles Moulliard <ch007m@gmail.com> wrote:

> Sorry.
>
> On Fri, Feb 5, 2016 at 6:45 PM, Eric Wittmann <notifications@github.com>
> wrote:
>
>> Can you re-submit on the /karaf branch instead of the /master branch?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/apiman/apiman/pull/357#issuecomment-180464750>.
>>
>
>
>
> --
> Charles Moulliard
> Apache Committer & PMC / Architect @RedHat
> Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io
>
>


-- 
Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by EricWittmann** [comment]
Most likely it's trying to load a class that isn't available to the osgi classloader.  This sort of thing is always a pain in the butt with osgi because of the way dependencies work there.

It's presumably trying to load PollCachingESRegistry, which lives in apiman-gateway-engine-es.jar.  If you've separated everything up into bundles, then it's likely that it can't be loaded.  

I guess solutions include creating an uber-bundle, or maybe we update the code to look in the osgi registry for services?

**Pull request closed without merging**
