### PR TITLE
Fix YAML API definitions not showing (#738)

### PR DESCRIPTION
**Pull request by owsega**
Fixes Issue apiman#738. It enables the showing of Swagger YAML API definitions in the ui

### CODE REVIEW

**Comment by volkflo** [comment]
This looks good :)

**Comment by EricWittmann** [comment]
Did you reformat whitespace or something for a couple of the files?  The github diff is brutal.  It's hard to tell what's changed.

**Comment by EricWittmann** [comment]
Or maybe line endings?  I guess it's fine - after looking a bit more closely I see that the additions are highlighted.  So +1 from me on this.

**Comment by owsega** [comment]
I think it's the line endings. I was initially surprised when I saw the heavy diffs too. Thank goodness for the highlights. I'd explore keeping original line endings next time

**Pull request merged**
