### PR TITLE
ci: build for Java 8, 11, and 15

### LINKED ISSUE #978: Add Java 11 and Java 15 builds to CI scripts

### PR DESCRIPTION
**Pull request by msavy**
Fixes #978

### CODE REVIEW

**Review by volkflo — DISMISSED** [review]
LGTM :) I like how simple GitHub solved this to use multiple versions of Java 🚀 
The problem while pulling an elastic image seems to be fixed now?

**Comment by msavy** [comment]
@volkflo Thanks for the feedback!

I think the ES image must be permissions related, because it doesn't complain when people with commit permissions do it. So the fix may still be needed for non-committers 🤔. May need a little investigation. I suspect a few little tweaks are all that is needed.

**Comment by volkflo** [comment]
@msavy I am not sure if it is a permission problem. I am also allowed to commit directly in this repository and the actions for my PR failed :D https://github.com/apiman/apiman/pull/965

**Comment by volkflo** [comment]
Seems that the CI will not start your build?
image

**Comment by msavy** [comment]
I noticed that yesterday. I think it's a glitch. I'll kick it again once
the other PR is in 👍. It isn't even showing in the actions menu, so
something has gone wonky in GitHub.

>
I tested the syntax locally and it works ok

**Pull request merged**
