### PR TITLE
re #803 UI Select

### PR DESCRIPTION
**Pull request by kahboom**
This basically just uses the `master` branch with the renaming changes and adds my Select2 > UI-Select changes on top of it. I had to merge the changes manually, so @jcechace I would really like it if you could run your tests against this fork and branch instead of the other.

JIRA: https://issues.jboss.org/browse/APIMAN-803
Other PR (outdated now): https://github.com/apiman/apiman/pull/292

cc  @EricWittmann

### CODE REVIEW

**Comment by EricWittmann** [comment]
This looks great!  I'll wait for @jcechace to run some tests before I merge, unless that takes too long. ;)

**Comment by jcechace** [comment]
I will be able to run them later today (currently I do not have access to vpn).  I will let you know the result at the latest tomorrow.

**Comment by EricWittmann** [comment]
Wow that's awesome, thanks!

**Comment by jcechace** [comment]
There seem to be some issues when creating contracts. 

1.  When directly accessing ```/apimanui/api-manager/new-contract``` and filling in the form, the "redirect" after hitting create ends with 404 under some circumstances
2. Client App version which are already registered are also displayed in the select. Not sure whether this is intentional as part of the "re-register" functionality (but it sure is confusing). 

It also seems that some elements on various places are slightly different. Jarek will have a look at that on Monday and us know.

**Comment by kasparjarek** [comment]
ad 1. This happend when user change ClientApp. The POST request to create contract is always send to the Client which was selected when the page had loaded.

**Comment by kahboom** [comment]
@kasparjarek - I was able to replicate this- POST request uses the Client App that was automatically selected on page load as opposed to the one manually selected after.

@jcechace - Is this on WF or Jetty? I'm attempting to replicate the first issue but haven't been able to.

As for the second issue, I asked @EricWittmann about this and yes, it is intentional. Changes are allowed to be made to registered clients, because there is a "re-register" action now.

**Comment by kahboom** [comment]
@jcechace - Actually, just replicated it, except I got a 409 error instead of 404. See screeenshot below. Looking in this now. Thanks!

screen shot 2015-12-21 at 10 10 06 am

**Comment by kasparjarek** [comment]
@kahboom I actually specified the first issue from @jcechace. I am sorry if it wasn't clear.

**Comment by kahboom** [comment]
Ahh, thanks @kasparjarek !

**Comment by jcechace** [comment]
@kahboom @EricWittmann  As for the second issue -- in that case we should display a sort of "reminder" that the changes won't take immediate effect.

**Comment by EricWittmann** [comment]
After creating a contract we redirect to the client details UI page - on
that page we can add something more obvious to indicate that the client has
changed since it was last published.  Could you add a jira for that?

**Comment by jcechace** [comment]
@EricWittmann  https://issues.jboss.org/browse/APIMAN-856

Though I still think that users should be able to distinguish already registered version when creating a contract (or performing any other operation really) as it will make you think whether you really want to do changes to already registered client.

**Comment by EricWittmann** [comment]
That's a fair point - maybe another jira then to enhance the New Contract
page with some sort of indicator showing the user that the client app they
selected has already been registered?

**Comment by jcechace** [comment]
@EricWittmann https://issues.jboss.org/browse/APIMAN-857

**Comment by kahboom** [comment]
@jcechace - Thanks for creating those jiras, I appreciate it. Would you mind re-testing? I just pushed up a fix for the issue where the incorrect app is used to create a new contract, and also a fix for another bug I came across where the submit button wouldn't always get enabled.

**Comment by jcechace** [comment]
@kahboom The issue should be fixed. 

However  there seems to be some delay in rest layer before the related endpoint starts returning the newly created contract.  Although it could be just a glitch in our tests (not able to reproduce manually). I will have to investigate further when I'm back from PTO -- this should not prevent merging.

**Pull request merged**
