### PR TITLE
fix(swagger-ui): fixed data transfer to swagger component

### PR DESCRIPTION
**Pull request by volkflo**
Fixes a couple of problems regarding tokens and swagger-ui.
Originally authored by @BastianGem

### CODE REVIEW

**Comment by volkflo** [comment]
This should fix the problems in #2502 

@ronimhd Could you please try out these changes. I would really appreciate it

@msavy I did had some conflicts because of the monorepo merge. So this should be tested before merging, even if I think I got all errors by now. Did not tested it in the upstream myself due to limited time.

**Comment by ronimhd** [comment]
@volkflo I was trying to help to test. I am not really familiar with node, even more Angular. And this following error happened when I tried build portal-ui in fix-swagger-ui-problem: 

`[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< io.apiman:apiman-portal-ui >---------------------
[INFO] Building apiman-portal-ui 3.2.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- git-commit-id-plugin:2.2.1:revision (get-the-git-infos) @ apiman-portal-ui ---
[INFO]
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ apiman-portal-ui ---
[INFO] Node v16.16.0 is already installed.
[INFO] NPM 8.15.0 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.6:npm (npm install (npm ci)) @ apiman-portal-ui ---
[INFO] Running 'npm ci' in /mnt/d/works/PDD/src/apiman/portal/ui
[WARNING] npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
[WARNING] npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[WARNING] npm WARN deprecated core-js@3.20.3: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[INFO]
[INFO] > apiman-developer-portal@3.0.0-SNAPSHOT prepare
[INFO] > cd ../../ && husky install portal/ui
[INFO]
[INFO] husky - Git hooks installed
[INFO]
[INFO] added 1428 packages, and audited 1429 packages in 8m
[INFO]
[INFO] 197 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO]
[INFO] 11 vulnerabilities (2 moderate, 9 high)
[INFO]
[INFO] To address issues that do not require attention, run:
[INFO]   npm audit fix
[INFO]
[INFO] To address all issues, run:
[INFO]   npm audit fix --force
[INFO]
[INFO] Run `npm audit` for details.
[INFO]
[INFO] --- maven-resources-plugin:3.3.0:resources (default-resources) @ apiman-portal-ui ---
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ apiman-portal-ui ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.3.0:testResources (default-testResources) @ apiman-portal-ui ---
[INFO] skip non existing resourceDirectory /mnt/d/works/PDD/src/apiman/portal/ui/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ apiman-portal-ui ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ apiman-portal-ui ---
[INFO] No tests to run.
[INFO]
[INFO] --- frontend-maven-plugin:1.6:npm (npm run-script prod) @ apiman-portal-ui ---
[INFO] Running 'npm run build-production-mvn' in /mnt/d/works/PDD/src/apiman/portal/ui
[INFO]
[INFO] > apiman-developer-portal@3.0.0-SNAPSHOT build-production-mvn
[INFO] > ng build --configuration production,java --output-path=target/classes/ --base-href=/portal/
[INFO]
[ERROR] - Generating browser application bundles (phase: setup)...
[ERROR] ✔ Browser application bundle generation complete.
[ERROR] ✔ Browser application bundle generation complete.
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/@swimlane/ngx-charts/fesm2015/swimlane-ngx-charts.mjs depends on 'clone-deep'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/keycloak-angular/fesm2015/keycloak-angular.mjs depends on 'keycloak-js'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/react-redux/es/components/connectAdvanced.js depends on 'hoist-non-react-statics'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on '@babel/runtime-corejs3/regenerator'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/camelCase'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/debounce'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/find'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/get'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/isEmpty'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/isFunction'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/isString'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/memoize'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/merge'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/omit'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/reduce'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/set'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/some'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/toLower'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/toString'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/upperFirst'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'lodash/zipObject'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'prop-types'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'randexp'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'react-copy-to-clipboard'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'react-debounce-input'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'react-immutable-proptypes'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'redux-immutable'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'url-parse'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js depends on 'xml-but-prettier'. CommonJS or AMD dependencies can cause optimization bailouts.
[ERROR] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/src/app/components/api-markdown-description/api-markdown-description.component.scss exceeded maximum budget. Budget 2.00 kB was not met by 224 bytes with a total of 2.22 kB.
[ERROR]
[ERROR] Warning: /mnt/d/works/PDD/src/apiman/portal/ui/src/app/components/my-apps/my-apps.component.scss exceeded maximum budget. Budget 2.00 kB was not met by 369 bytes with a total of 2.36 kB.
[ERROR]
[ERROR] Warning: ▲ [WARNING] Expected identifier but found "*"
[ERROR]
[ERROR]     styles.f70aa4f993ac4664.css:4560:30205:
[ERROR]       4560 │ ...er{clear:both}.swagger-ui .cf{*zoom:1}.swagger-ui .cl{clear:l...
[ERROR]            ╵                                  ^
[ERROR]
[ERROR]
[ERROR]
[ERROR]
[ERROR]
[ERROR] Error: src/app/components/swagger/swagger.component.html:19:5 - error NG8001: 'app-img-or-icon-selector' is not a known element:
[ERROR] 1. If 'app-img-or-icon-selector' is an Angular component, then verify that it is part of this module.
[ERROR] 2. If 'app-img-or-icon-selector' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
[ERROR]
[ERROR] 19     <app-img-or-icon-selector
[ERROR]        ~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR] 20       [imgUrl]="this.apiVersion.api.image"
[ERROR]    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR] 21       [dimension]="imgSize"></app-img-or-icon-selector>
[ERROR]    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]
[ERROR]   src/app/components/swagger/swagger.component.ts:35:16
[ERROR]     35   templateUrl: './swagger.component.html',
[ERROR]                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     Error occurs in the template of component SwaggerComponent.
[ERROR]
[ERROR]
[ERROR] Error: src/app/components/swagger/swagger.component.html:20:7 - error NG8002: Can't bind to 'imgUrl' since it isn't a known property of 'app-img-or-icon-selector'.
[ERROR] 1. If 'app-img-or-icon-selector' is an Angular component and it has 'imgUrl' input, then verify that it is part of this module.
[ERROR] 2. If 'app-img-or-icon-selector' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
[ERROR] 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
[ERROR]
[ERROR] 20       [imgUrl]="this.apiVersion.api.image"
[ERROR]          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]
[ERROR]   src/app/components/swagger/swagger.component.ts:35:16
[ERROR]     35   templateUrl: './swagger.component.html',
[ERROR]                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     Error occurs in the template of component SwaggerComponent.
[ERROR]
[ERROR]
[ERROR] Error: src/app/components/swagger/swagger.component.html:21:7 - error NG8002: Can't bind to 'dimension' since it isn't a known property of 'app-img-or-icon-selector'.
[ERROR] 1. If 'app-img-or-icon-selector' is an Angular component and it has 'dimension' input, then verify that it is part of this module.
[ERROR] 2. If 'app-img-or-icon-selector' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
[ERROR] 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
[ERROR]
[ERROR] 21       [dimension]="imgSize"></app-img-or-icon-selector>
[ERROR]          ~~~~~~~~~~~~~~~~~~~~~
[ERROR]
[ERROR]   src/app/components/swagger/swagger.component.ts:35:16
[ERROR]     35   templateUrl: './swagger.component.html',
[ERROR]                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     Error occurs in the template of component SwaggerComponent.
[ERROR]
[ERROR]
[ERROR]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18:43 min
[INFO] Finished at: 2023-04-12T17:07:56+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run-script prod) on project apiman-portal-ui: Failed to run task: 'npm run build-production-mvn' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
ronim@DESKTOP-E1N55F7:/mnt/d/works/PDD/src/apiman/portal/ui$`

**Comment by msavy** [comment]
It's likely because their downstream is using different dependency versions that are incompatible. It probably requires a bit of tweaking of the deps and it should (hopefully) work.

**Comment by volkflo** [comment]
I pushed a fixup, it should build now we the latest changes (forgot to cherry pick a few things).
@ronimhd I would appreciate if you could test it again and give us feedback, thanks.

**Comment by ronimhd** [comment]
@volkflo I have tried again build the branch, and now it was success. And then I created a branch from 3.1.1.Final tag and then merged/cherry pick from fix_swagger_ui branch only portal ui patch. And then deploy and in test in my local. Now Api Documentation is working properly without login

**Comment by msavy** [comment]
Thanks for confirming, I'll try to get it into the next point release. 

Reminder to self — need to add a changelog entry

**Review by msavy — APPROVED** [review]

**Comment by msavy** [comment]
Thanks, everyone. Much appreciated!

**Pull request merged**
