### PR TITLE
Cleanup apiman warnings

### PR DESCRIPTION
**Pull request by msavy**
Please don't merge this yet - it breaks GWT.

However, I thought I'd push this early for review as it fixes warnings + docs issues (for java 8) in engine & core.

Once we kill GWT I will rebase it and we can merge.

Please let me know if I missed anything.

### CODE REVIEW

**Comment by msavy** [comment]
BTW, this is yet another good reason to get rid of GWT. They still don't have proper support for Java 7, let alone Java 8.

**Comment by EricWittmann** [comment]
Agreed.

**Comment by msavy** [comment]
I've rebased this onto master so it should be good to go, tests are green

**Comment by msavy** [comment]
552 to go

**Pull request merged**
