### PR TITLE
Fixes TimeRestrictedAccessPolicy bounds checks (Fixes  #664)

### LINKED ISSUE #664: [Bug]TimeRestrictedAccessPolicy
Hi,

The method of **TimeRestrictedAccessPolicy** named **matchesDay** has a judgemental problem. Which in lines number 161, origin code `return dayNow <= dayEnd && dayNow <= dayStart;`, should change to `return dayNow <= dayEnd && dayNow >= dayStart;`.

### PR DESCRIPTION
**Pull request by MosesFu**
fixed #664 
The **TimeRestrictedAccessPolicy** has another bug found, I will post later.

### CODE REVIEW

**Comment by EricWittmann** [comment]
Any way to test this, I wonder?  Might be difficult to accomplish - testing time/date functionality can be a pain.

**Comment by msavy** [comment]
One thought I had was that we could spin the code that assesses the date/time into a helper class and then write some unit tests against it.

**Comment by msavy** [comment]
I'll merge this and do improvements separately.

**Comment by msavy** [comment]
Thank you for your contribution @MosesFu! It is much appreciated.

**Pull request merged**
