### PR TITLE
test(test-common): TestPlanRunner retry up to 4 times on IOException

### LINKED ISSUE #1308: Retry initial connection attempts for policy & rest-test test frameworks
Occasionally CI seems to have an issue where it is unable to connect to localhost, you'll see errors like 

```
2021-06-14T08:27:30.9857660Z [ERROR] Tests run: 4, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.094 s <<< FAILURE! - in io.apiman.gateway.test.SimpleSharedStatePolicyTest
2021-06-14T08:27:30.9869295Z [ERROR] io.apiman.gateway.test.SimpleSharedStatePolicyTest.Echo 1  Time elapsed: 0.002 s  <<< ERROR!
2021-06-14T08:27:30.9907397Z java.lang.Error: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8082 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
2021-06-14T08:27:30.9919844Z Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8082 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
2021-06-14T08:27:30.9925004Z Caused by: java.net.ConnectException: Connection refused
2021-06-14T08:27:30.9926390Z 
```

It's probably just a race condition where the webserver for the test hasn't finished starting up yet, or perhaps some other timing issue around binding to the OS socket. Either way, a simple wait-then-retry loop will likely sort this occasional annoyance out.

### PR DESCRIPTION
**Pull request by msavy**
Fixes #1308

### CODE REVIEW

**Comment by msavy** [comment]
Pls squash merge when approved

**Review by volkflo — COMMENTED** [review]
@msavy Interesting! I also looked into the Docs of jcabi.
Can you shortly explain whats the advantage of your code and why you are not using the already existing RetryWire(https://www.javadoc.io/doc/com.jcabi/jcabi-http/1.17/com/jcabi/http/wire/RetryWire.html)? I think this is about the response status codes but I am not 100% sure :)

**Comment by msavy** [comment]
> @msavy Interesting! I also looked into the Docs of jcabi.
> Can you shortly explain whats the advantage of your code and why you are not using the already existing RetryWire(https://www.javadoc.io/doc/com.jcabi/jcabi-http/1.17/com/jcabi/http/wire/RetryWire.html)? I think this is about the response status codes but I am not 100% sure :)

Correct. I tried the built-in retrywire, however this interferes with the tests because it retries on a few tests when a 5xx error is (legitimately) returned.

All we're trying to do is try again in the case that we can't connect (probably a small and rare race condition).

**Review by volkflo — APPROVED** [review]

**Comment by msavy** [comment]
Please feel free to rebase merge whenever you are satisfied with the pull
request.

Thanks for the review!

**Pull request merged**
