### PR TITLE
Support Java 11

### PR DESCRIPTION
**Pull request by bekihm**
I added some missing maven dependencies to support the build on java 11.
Unfortunately I could not modify the github verify.yml to switch to java 11.

I compiled it locally with the adopt-openj9-11.

See also the update on the apiman plugins here:
https://github.com/apiman/apiman-plugins/pull/102

### CODE REVIEW

**Comment by bekihm** [comment]
I was able to change the version via github web editor :-)

**Comment by volkflo** [comment]
Great that you started with this. Did you start to investigate the problem with LDAP?

**Comment by bekihm** [comment]
@volkflo Not yet, I think @msavy hit the same problem which he has mentioned in the corresponding elasticsearch issue.

**Comment by msavy** [comment]
This is something I have not yet had time to resolve, unfortunately. Things at my startup are quite difficult at the moment, so finding time to spare difficult. It's certainly doable.

**Comment by msavy** [comment]
Has been superseded by #973

**Pull request closed without merging**
