### PR TITLE
Changes for APIMAN-942 - Ability to delete an unpublished service.

### PR DESCRIPTION
**Pull request by ctsantiago**
This is a proposed change described in:
https://issues.jboss.org/browse/APIMAN-942

### CODE REVIEW

**Comment by EricWittmann** [comment]
This is a great start, thanks!

*Note*: I am going to make the following changes to this PR:
* The endpoint to DELETE an API:
```
    @DELETE
    @Path("{organizationId}/apis/{apiId}")
    public void deleteApi(@PathParam("organizationId") String organizationId,
            @PathParam("apiId") String apiId)
            throws ApiNotFoundException, NotAuthorizedException, InvalidApiStatusException;
```
* The user will need to have the "apiAdmin" privilege to delete, rather than full Admin privs

**Comment by EricWittmann** [comment]
OK @ctsantiago  - merged and modified.  Please have a look and let me know if the solution still works for you! :)

**Comment by ctsantiago** [comment]
Thanks Eric.  I learned a lot from your changes for next time.  This works for us.

**Comment by EricWittmann** [comment]
OK great!  I think there is still work to be done on the Delete API feature - but it should be a good start.  For example, I'd like it to work provided there are *no* published APIs.  But that means when an API is retired we need to break all its contracts.  Or else we need to break the contracts when deleting it (that's probably the way to go).

But for now this gets us some common use cases (e.g. I created an API and never published it, but now I can't delete it!).  :)

We also still need to work on deleting Plans, Orgs, and Clients.  Again, I think this PR is a good start to all that work.

**Pull request merged**
