### PR TITLE
Fix cache with different query params

### PR DESCRIPTION
**Pull request by alesuffleur**
The buildCacheID method ignored the query params.
I added a md5 of query params.

Maybe it's better to make a hash of rawrequest to cache POST/ PUT/PATCH verb.

### CODE REVIEW

**Comment by bekihm** [comment]
What is the status about this Pull-Request? Otherwise we cannot use the Caching-Policy.

**Comment by msavy** [comment]
I haven't had time to work with it yet (probably needs an additional option in the UI also). 

Unfortunately, I'm not able to spend a lot of time on this at the moment, but I'll try to get around to it shortly.

What's your use-case? Do you just cache a response if all query parameters are the same, or do you need to be able to pay attention to a subset?

**Comment by alesuffleur** [comment]
> "What's your use-case? Do you just cache a response if all query parameters are the same, or do you need to be able to pay attention to a subset?"


For example, when you have a web service with pagination:
- http://mygateway/webservice/documentation?page=1
- http://mygateway/webservice/documentation?startItem=50

**Comment by msavy** [comment]
Sure, but I just mean in the case when you haves several query parameters, e.g.: ?a=123&unimportant=foo

Would one expect this to be configurable so that (e.g.) `a=123` is part of the cache key, but `unimportant=foo` is not?

**Comment by msavy** [comment]
Thanks, I understand. 

I’ll try to work with it shortly to integrate the feature.

Apologies for not being as active any more — just an issue of my employer wanting me to work primarily on another area at the moment.

**Comment by bekihm** [comment]
We can also offer to test this Pull-Request and extend it for our purpose described above.

**Comment by bekihm** [comment]
I think this PR is now closed by [PR 712](https://github.com/apiman/apiman/pull/712).

**Pull request closed without merging**
