### PR TITLE
re #826 Add ability to dismiss popover with close button

### PR DESCRIPTION
**Pull request by kahboom**
Changes:
- Added a close icon to the top right hand corner of the 'Why Can't I Publish?' checklist popover. Clicking the icon results in a closed popover.
- Needed to re-add the ability to toggle the popover by clicking on the same 'Why Can't I Publish?' button that opens the popover. Added a check in the controller for this.

JIRA: https://issues.jboss.org/browse/APIMAN-826

Screenshot:
screen shot 2015-12-18 at 11 09 15 am

cc @EricWittmann

### CODE REVIEW

**Comment by kahboom** [comment]
@EricWittmann - Just an aside, it looks like there will be support in the future to close the popover by clicking anywhere outside of it (I mean natively via the UI-Bootstrap Popover directive), but if you'd like this feature soon I can have a go at it and will create a JIRA. Let me know.

**Comment by EricWittmann** [comment]
Waiting for the official support for that is fine with me.

**Comment by kahboom** [comment]
@EricWittmann - Are we missing anything for this to be merged in?

**Comment by EricWittmann** [comment]
No - I was just waiting for your other PR to be merged first... not sure why. :

**Pull request merged**
