### PR TITLE
refactor(es): revert waitUntil index refresh strategy. Use immediate.

### PR DESCRIPTION
**Pull request by msavy**
Let's try this out... We can likely pick and choose which is appropriate.

### CODE REVIEW

**Comment by volkflo** [comment]
Immediate will not work for all UI pages because sometimes then the information is missing that you just created. 
I think we have to put a little more logic behind it :)

**Comment by msavy** [comment]
The Elastic javadoc indicates that this should force an immediate refresh, whereas wait_for waits for Elastic's  refresh interval and the notifies you.

From the docs for "refresh=true" (aka immediate):

> Refresh the relevant primary and replica shards (not the whole index) immediately after the operation occurs, so that the updated document appears in search results immediately. This should ONLY be done after careful thought and verification that it does not lead to poor performance, both from an indexing and a search standpoint.
> 
> Force a refresh as part of this request. This refresh policy does not scale for high indexing or search throughput but is useful to present a consistent view to for indices with very low traffic. And it is wonderful for tests!
> 

This should work as far as I can tell? If it doesn't, perhaps we need to add a couple of less common healthcheck waits or similar.

**Comment by volkflo** [comment]
I will try to test this :)

**Comment by msavy** [comment]
> I will try to test this :)

Thanks!

**Comment by volkflo** [comment]
@BastianGem and I tested this, looks good. Faster than before. 
I think we can merge! 🚀

**Comment by msavy** [comment]
Fantastic, thanks!

Will double check I have everything covered and then merge in.

**Review by BastianGem — DISMISSED** [review]
LGTM :)
Performance is definitely increased, which is very noticeable with the Import-Feature

**Comment by msavy** [comment]
I'll fix the comments and then ask you guys for a green tick. Thanks

**Review by volkflo — APPROVED** [review]
Fantastic, we have a faster UI experience again! :)

**Pull request merged**
