### PR TITLE
Config option to enable admin-only creates for organizations

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Comment by EricWittmann** [comment]
This attempts to address https://github.com/apiman/apiman/issues/817

**Comment by EricWittmann** [comment]
@volkflo and @tevosouza - how does this look to you?

**Comment by volkflo** [comment]
@EricWittmann Cool that you have already implemented this 👍  For me this is fine :)

There are just two little things:
I stumbled over this for the UI.
https://github.com/apiman/apiman/blob/e14d18ec74b20a675591fa0384ead48e55519f3c/manager/ui/war/plugins/api-manager/ts/dash.ts#L4-L11
I am not sure if something of this is still used somewhere.

And the other point is that it would be great if you could add the new system property into the `apiman.properties` files directly. So we know in a few weeks that there is an option we can configure without looking into the code :)

**Comment by EricWittmann** [comment]
Yeah I didn't hook the option into the UI yet.  I'll need to do that as well - thanks for tracking down where that would be done!  I honestly can't remember why Org Creation was disabled for those platforms.... technical debt!

**Comment by tevosouza** [comment]
@EricWittmann this is fine for me!
Thanks a lot!

**Comment by EricWittmann** [comment]
OK @tevosouza and @volkflo - please have one last look at this PR.  I updated it include UI changes.  Opinions welcome. :)

**Comment by tevosouza** [comment]
@EricWittmann looks good to me, I have no comments to add
Thanks!

**Comment by EricWittmann** [comment]
Good point @volkflo - I've reverted `yarn.lock` since I didn't make any `package.json` changes.  I'm going to merge this and then add the property to `apiman.properties` as you suggested in a separate PR (along with a fix for the Swagger UI problem when running in Wildfly).

**Pull request merged**
