### PR TITLE
Refactor duplicate code DefaultEsClientFactory/DefaultESClientFactory

### PR DESCRIPTION
**Pull request by bekihm**
I refactored the two classes Default**Es**ClientFactory (in package io.apiman.manager.api.es) and Default**ES**ClientFactory (in package io.apiman.gateway.engine.es) to one single class (in io.apiman.common.es.util) because they do almost the same thing.
This hopefully reduces confussions during debugging because of the similar class naming and reduces code duplication. Finally I also modified the apiman.properties files to unify the elasticsearch access properties in the json files of the vertx gateway which was different in the two Default(Es/ES)ClientFactories.

As consequence I had to modify the tests to use the new refactored DefaultEsClientFactory class and modified the maven poms to use the new class.

Before the refactoring the class structure looked like this:

**Package of io.apiman.manager.api.es.DefaultEsClientFactory**
DefaultEsClientFactory_klein_es

**package of io.apiman.gateway.engine.es.DefaultESClientFactory**
DefaultESClientFactory

After the refactoring we have to following class structure:

**Package of previous io.apiman.manager.api.es.DefaultEsClientFactory**
AfterRefactoringDefaultEsClientFactory_manager_es

**Package of previous io.apiman.gateway.engine.es.DefaultESClientFactory**
AfterRefactoringDefaultEsClientFactory_engine_es

**Package of io.apiman.common.es.util**
AfterRefactoringDefaultEsClientFactory

### CODE REVIEW

**Comment by EricWittmann** [comment]
This seems like a very nice improvement, thank you.  I will review and merge soon.

**Comment by bekihm** [comment]
Nice to hear :-)

I have to thank also @volkflo who has reviewed the changes before the PR was done.

**Comment by msavy** [comment]
Have you guys checked that this doesn't break the Vert.x implementation?

In particular, I noticed you changed some config keys, which might require changes in docs and vert.x JSON config examples (perhaps not, but worth checking).

**Comment by volkflo** [comment]
Yes, we have checked that (we are only using the vert.x version).
The config JSONs for the vert.x gateway are already in the "correct" format with `client` like:
```json
 // Elasticsearch Metrics Settings
  "metrics": {
    "class": "io.apiman.gateway.engine.es.ESMetrics",
    "config": {
      "client": {
        "type": "jest",
        "protocol": "${apiman.es.protocol}",
        "host": "${apiman.es.host}",
```
So @bekihm changed the settings so that we can use this style everywhere because in the `.properties` file the most keys didn't have the `.client` in the key. This was confusing for us and so we decided to change the `.properties` files.

But the documentation is a good hint, we did not check your docs. We can do this an provide an PR for this also.

A little addition to the failed test, we have no access to the snyk project so we could not check what wrong there.

**Comment by EricWittmann** [comment]
I think this is a nice change.  I am also unable to access Snyk to see what the issues are.  However, Travis passes which is the more important check IMO.

**Comment by bekihm** [comment]
We are curious to hear remarks on this. :-)

**Comment by EricWittmann** [comment]
I think the change is very good - pretty hilarious that we had two classes with almost the same name and doing the same basic thing.  Glad to have them combined.  I'm just trying to figure out what Snyk is complaining about, as I don't currently have access to it.

Thank you for the reminder though - I've pinged Marc again and hopefully he can give me the 411 or even better grant me access to snyk! :)

**Comment by EricWittmann** [comment]
While we wait, @bekihm can you have a look at the conflicts that this PR now has?

**Comment by msavy** [comment]
The security issues are coincidentally popping up because they have been disclosed recently. This is good to merge.

**Pull request merged**
