### PR TITLE
build(vertx): Update lmax disruptor to 3.4.2

### LINKED ISSUE #778: Log4J update has broken vert.x gateway
It seems that the log4j update to 2.12.0 has broken the vert.x gateway

```java
Exception in thread "main" java.lang.NoSuchMethodError: com.lmax.disruptor.dsl.Disruptor.<init>(Lcom/lmax/disruptor/EventFactory;ILjava/util/concurrent/ThreadFactory;Lcom/lmax/disruptor/dsl/ProducerType;Lcom/lmax/disruptor/WaitStrategy;)V
gateway          |      at org.apache.logging.log4j.core.async.AsyncLoggerDisruptor.start(AsyncLoggerDisruptor.java:102)
gateway          |      at org.apache.logging.log4j.core.async.AsyncLoggerContext.start(AsyncLoggerContext.java:75)
gateway          |      at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
gateway          |      at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
gateway          |      at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
gateway          |      at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:661)
gateway          |      at io.apiman.gateway.platforms.vertx3.logging.ApimanLog4j2LogDelegate.<init>(ApimanLog4j2LogDelegate.java:21)
gateway          |      at io.apiman.gateway.platforms.vertx3.logging.ApimanLog4j2LogDelegateFactory.createDelegate(ApimanLog4j2LogDelegateFactory.java:9)
gateway          |      at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:74)
gateway          |      at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:67)
gateway          |      at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:45)
gateway          |      at io.vertx.core.impl.launcher.commands.BareCommand.<init>(BareCommand.java:49)
gateway          |      at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:39)
gateway          |      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
gateway          |      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
gateway          |      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
gateway          |      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
gateway          |      at java.lang.Class.newInstance(Class.java:442)
gateway          |      at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:32)
gateway          |      at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:44)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:158)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:213)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
gateway          |      at io.apiman.gateway.platforms.vertx3.ApimanLauncher.main(ApimanLauncher.java:48)
```

### PR DESCRIPTION
**Pull request by msavy**
Fixes #778

### CODE REVIEW

**Comment by msavy** [comment]
@volkflo check it out

**Comment by volkflo** [comment]
Looks better but still getting errors:

```java
gateway          | 2019-11-20 14:43:52,719 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.config.LoggersPlugin for element Loggers: java.lang.IllegalStateException: Configuration has multiple root loggers. There can be only one. java.lang.reflect.InvocationTargetException   
gateway          |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gateway          |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gateway          |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gateway          |      at java.lang.reflect.Method.invoke(Method.java:498)
gateway          |      at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)
gateway          |      at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
gateway          |      at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
gateway          |      at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
gateway          |      at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
gateway          |      at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
gateway          |      at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:548)
gateway          |      at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:620)
gateway          |      at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:637)
gateway          |      at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
gateway          |      at org.apache.logging.log4j.core.async.AsyncLoggerContext.start(AsyncLoggerContext.java:76)
gateway          |      at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
gateway          |      at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
gateway          |      at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
gateway          |      at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:661)
gateway          |      at io.apiman.gateway.platforms.vertx3.logging.ApimanLog4j2LogDelegate.<init>(ApimanLog4j2LogDelegate.java:21)
gateway          |      at io.apiman.gateway.platforms.vertx3.logging.ApimanLog4j2LogDelegateFactory.createDelegate(ApimanLog4j2LogDelegateFactory.java:9) 
gateway          |      at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:74)
gateway          |      at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:67)
gateway          |      at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:45)
gateway          |      at io.vertx.core.impl.launcher.commands.BareCommand.<init>(BareCommand.java:49)
gateway          |      at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:39)
gateway          |      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
gateway          |      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
gateway          |      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
gateway          |      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
gateway          |      at java.lang.Class.newInstance(Class.java:442)
gateway          |      at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:32)
gateway          |      at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:44)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:158)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:213)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
gateway          |      at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
gateway          |      at io.apiman.gateway.platforms.vertx3.ApimanLauncher.main(ApimanLauncher.java:48)
gateway          | Caused by: java.lang.IllegalStateException: Configuration has multiple root loggers. There can be only one.
gateway          |      at org.apache.logging.log4j.core.config.LoggersPlugin.createLoggers(LoggersPlugin.java:49)
gateway          |      ... 38 more
gateway          |
gateway          | 2019-11-20 14:43:52,757 main WARN No Loggers were configured, using default. Is the Loggers element missing?
```

**Comment by msavy** [comment]
https://www.youtube.com/watch?v=sqcLjcSloXs

**Comment by msavy** [comment]
Hmm, hopefully that should fix it?

**Comment by volkflo** [comment]
Great! LGTM :)

```java
gateway          | [INFO ] 2019-11-20 15:12:35.777 [vert.x-eventloop-thread-0] InitVerticle - Starting verticle: INITIALISER. UUID: ae4c7730-e201-474f-8282-88d526c5a8be.INITIALISER.
gateway          | [INFO ] 2019-11-20 15:12:35.824 [vert.x-eventloop-thread-0] InitVerticle - Will deploy 1 of type API
gateway          | [INFO ] 2019-11-20 15:12:35.841 [vert.x-eventloop-thread-0] InitVerticle - Will deploy 0 of type HTTP
gateway          | [INFO ] 2019-11-20 15:12:35.841 [vert.x-eventloop-thread-0] InitVerticle - Will deploy 2 of type HTTPS
gateway          | [INFO ] 2019-11-20 15:12:35.848 [vert.x-eventloop-thread-1] ApiVerticle - Starting verticle: API. UUID: 9cdb4ff7-5eda-440e-827a-40b279fa8d7c.API.
gateway          | [INFO ] 2019-11-20 15:12:35.909 [vert.x-eventloop-thread-3] HttpsGatewayVerticle - Starting verticle: HTTPS. UUID: 26d5421b-495e-4960-a7a9-70732261a209.HTTPS.
gateway          | [INFO ] 2019-11-20 15:12:35.937 [vert.x-eventloop-thread-2] HttpsGatewayVerticle - Starting verticle: HTTPS. UUID: 4f44b0df-7cef-4807-abf9-3036b37944f2.HTTPS.
gateway          | [WARN ] 2019-11-20 15:12:38.022 [vertx-blocked-thread-checker] BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2174 ms, time limit is 2000 ms
gateway          | [WARN ] 2019-11-20 15:12:38.022 [vertx-blocked-thread-checker] BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 2114 ms, time limit is 2000 ms
gateway          | [WARN ] 2019-11-20 15:12:38.022 [vertx-blocked-thread-checker] BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2147 ms, time limit is 2000 ms
gateway          | [WARN ] 2019-11-20 15:12:39.023 [vertx-blocked-thread-checker] BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3175 ms, time limit is 2000 ms
gateway          | [WARN ] 2019-11-20 15:12:39.023 [vertx-blocked-thread-checker] BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 3114 ms, time limit is 2000 ms
gateway          | [WARN ] 2019-11-20 15:12:39.023 [vertx-blocked-thread-checker] BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3148 ms, time limit is 2000 ms
gateway          | [INFO ] 2019-11-20 15:12:40.005 [vert.x-eventloop-thread-0] InitVerticle - Apiman Version: 7.6.0
gateway          | [INFO ] 2019-11-20 15:12:40.029 [vert.x-eventloop-thread-0] InitVerticle - Vert.x Version: 3.7.0
gateway          | [INFO ] 2019-11-20 15:12:40.031 [vert.x-eventloop-thread-0] InitVerticle - Successfully deployed all verticles
gateway          | [INFO ] 2019-11-20 15:12:40.032 [vert.x-eventloop-thread-0] InitVerticle - Gateway API port: 8,081
gateway          | [INFO ] 2019-11-20 15:12:40.033 [vert.x-eventloop-thread-3] VertxIsolatedDeployer - Succeeded in deploying verticle
```

**Comment by msavy** [comment]
Okay, great. If nobody else has thoughts on this, I'll rebase & merge in shortly.

**Pull request merged**
