### PR TITLE
Merge Karaf branch with master

### PR DESCRIPTION
**Pull request by cmoulliard**
Lot of pain and work but finally the job has been done to merge karaf with master. Thank to Marc (the Git guru) & Rachel (the git butcher) ;-)

### CODE REVIEW

**Comment by EricWittmann** [comment]
@kahboom - are you gonna take that?! ;)

**Comment by msavy** [comment]
The branch doesn't build, I'm afraid (see CI failure). Same  locally.

**Comment by cmoulliard** [comment]
What is the error reported ?

**Comment by msavy** [comment]
Look on the CI. Same as there.

**Comment by cmoulliard** [comment]
What is the link to the CI Server ?

On Mon, Apr 4, 2016 at 10:45 AM, Marc Savy <notifications@github.com> wrote:

> Look on the CI. Same as there.
>
> On Mon, 4 Apr 2016, 09:32 Charles Moulliard, <notifications@github.com>
> wrote:
>
> > What is the error reported ?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/apiman/apiman/pull/445#issuecomment-205194143>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/apiman/apiman/pull/445#issuecomment-205198205>
>



-- 
Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by cmoulliard** [comment]
Do you also have "dependencies.dependency.version" errors locally ? Can I
fix them and push the modifications ?

On Mon, Apr 4, 2016 at 10:48 AM, Charles Moulliard <ch007m@gmail.com> wrote:

> What is the link to the CI Server ?
>
> On Mon, Apr 4, 2016 at 10:45 AM, Marc Savy <notifications@github.com>
> wrote:
>
>> Look on the CI. Same as there.
>>
>> On Mon, 4 Apr 2016, 09:32 Charles Moulliard, <notifications@github.com>
>> wrote:
>>
>> > What is the error reported ?
>> >
>> > —
>> > You are receiving this because you commented.
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/apiman/apiman/pull/445#issuecomment-205194143>
>>
>> >
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/apiman/apiman/pull/445#issuecomment-205198205>
>>
>
>
>
> --
> Charles Moulliard
> Apache Committer & PMC / Architect @RedHat
> Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io
>
>


-- 
Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by msavy** [comment]
Yes, it’s the same locally. Please look at the travis CI build log which is linked on your pull request.

**Comment by cmoulliard** [comment]
What is the next step before to apply the PR ?

**Comment by EricWittmann** [comment]
We have to code review it.  I don't have an ETA because we have a lot of product related tasks on our plate.  I might merge this onto a branch that I will keep up to date as we make changes on master.

**Comment by cmoulliard** [comment]
The existing PR doesn't break the current project so you could apply it on
master to prepare 1.2.4. I can make additional tests top of JBoss Fuse
6.2.1 (or 6.3 announced soon) to control also that the test coverage of the
gateway are suffisant and that it works with next Fuse delivery

I will nevertheless continue to improve it what has been done by adding
additional tests for the gateway, add option to switch authentication mode
between keycloak, karaf or none, ...

On Tue, Apr 5, 2016 at 7:51 PM, Eric Wittmann <notifications@github.com>
wrote:

> We have to code review it. I don't have an ETA because we have a lot of
> product related tasks on our plate. I might merge this onto a branch that I
> will keep up to date as we make changes on master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apiman/apiman/pull/445#issuecomment-205917978>
>



-- 
Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by cmoulliard** [comment]
Can we merge this PR please (see my last comment) ?

**Comment by EricWittmann** [comment]
I understand your point (the PR doesn't break the current project) but unfortunately we cannot merge onto master without at least a cursory review of the code.  I will do that as soon as I can, but I have several very high priority tasks ahead of this.  

I realize it's probably frustrating, and I'm sorry about that.

The good news is that now that you've squashed the commits down to a reasonable number, it will be easier to merge with master.  What I *may* do is replace the existing "karaf" branch with this PR for now.

**Comment by jajansen** [comment]
+1 
I would really like to be able to deploy the gateway on Fuse 6.2.x as well.

**Comment by EricWittmann** [comment]
Closing due to the project being deprecated.

**Pull request closed without merging**
