### PR TITLE
Added skipIfFileExists flag to the ant get task

### PR DESCRIPTION
**Pull request by kunallimaye**
# Maven profile install-all-wildfly8
This profile by default downloads the wildfly binary from the net. Adding a check to the ant get task to check if we already have the binary and skip that task if the binary exists locally.
> skipexisting="true"

### CODE REVIEW

**Comment by msavy** [comment]
@EricWittmann AFAICT we already do this? Certainly seems to be the behaviour on my machine.

@kunallimaye Unfortunately your editor has reformatted and indented the XML so drastically I can't actually inspect the diff in a useful fashion. Every line shows as changed.

**Comment by EricWittmann** [comment]
Yeah strange.  The ant docs suggest that skipexisting defaults to false but it seems to work for me anyway.  That said I'm happy to add the flag anyway.  

+1 on the formatting problems though.  Are there any other changes in there?

**Comment by kunallimaye** [comment]
Nope no other changes. 
Happy to submit one with original formatting if required. Please let us know. 
--kl

--
Kunal Limaye

**Comment by EricWittmann** [comment]
It's ok - that's a simple enough change that I just went ahead and made it:

https://github.com/apiman/apiman/commit/e970378d49a07c3e2a630ccffc43cf0eb67eb1ea

**Pull request closed without merging**
